apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy2shop-deployment
  labels:
    app: easy2shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy2shop
  template:
    metadata:
      labels:
        app: easy2shop
    spec:
      containers:
        - name: easy2shop
          image: easy2shop:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

          # Health checks (recommended)
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
