apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy2shop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easy2shop
  template:
    metadata:
      labels:
        app: easy2shop
    spec:
      containers:
        - name: easy2shop
          image: easy2shop:latest
          ports:
            - containerPort: 5000
